apiVersion: v1
kind: Service
metadata:
  name: designvikings-us-web
spec:
  selector:
    app: designvikings-us-web
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 80
      nodePort: 30006
  type: NodePort